### ISSUE TITLE
Versioning : Invalid version

### ISSUE THREAD

**Issue by darMed** [RecastAI/SDK-NodeJS#18]
Hello everyone!
Am new on using recast Ai and I have a problem integratinga chat bot to my IONIC 2 project.
Here is the error:
Invalid Version,
![recast err](https://cloud.githubusercontent.com/assets/26750063/25840551/8886998e-349c-11e7-94ce-fda260ea6eb4.PNG)
This happens after I have imported the library recatstai and called the request with the correcponding token.
Node version 6.9.1
Npm version 3.10.8

**Comment by JulienBlancher** [comment]
Hello darMed,
I don't see any recast-ai file loaded in your backtrace. Are you sure this is an issue due to Recast.AI?
Can you comment the code dealing with Recast.AI and try again to check is the error disappears or not?

**Comment by darMed** [comment]
@JulienBlancher 
Actually
the error cames whe I make a call to my bot.

import { recastai } from 'recastai';
public client = new recastai('be666b5ecf36c5a206b5a8ad09bca444');

**Comment by jhoudan** [comment]
Hi,

What's the version of the recastai module you've installed? If it's the 3.3.0, you need to update it to a newer version, like 3.3.1

**Comment by mellisdesigns** [comment]
@darMed might want to remove that key in your comment if it's real. 👍

**Comment by darMed** [comment]
It's oki solved the problem
my semver version was outdated
