### ISSUE TITLE
RecastAI does not match entities from conversation text that had no problem before.

### ISSUE THREAD

**Issue by mellisdesigns** [RecastAI/SDK-NodeJS#20]
Hey Guys

I have been working on a bot, and my entities have been coming through perfectly. Tried tonight, and now I am not getting any matched entities. The testing text has not changed at all.

![image](https://cloud.githubusercontent.com/assets/629570/26061476/9cef9330-39ba-11e7-8ece-ffba7e3ab06a.png)

![image](https://cloud.githubusercontent.com/assets/629570/26061500/b262fd74-39ba-11e7-8adf-4c8e336e7983.png)

Has anything changed drastically on how the request is processed. I am using `recastai` node package.

**Comment by PaulRenvoise** [comment]
Hi @mellisdesigns,
Please open a new issue on https://github.com/RecastAI/Recast.AI as this does not concern the NodeJS SDK. In the meantime, I'll look at what's happening with your bot.
Cheers,
