### ISSUE TITLE
recastai is not a constructor

### ISSUE THREAD

**Issue by gururajmbhandarkar** [RecastAI/SDK-NodeJS#22]
Hi,
returns recastai is not a constructor for nodejs v6.10.2. didn't test with other versions.. please check
`const recastai = require('recastai');`
`const client = new recastai(config.recast);`

**Comment by mandre42** [comment]
Hello @gururajmbhandarkar 
You just have to edit the following line:
`const recastai = require('recastai');`
by
`const recastai = require('recastai').default;`

I already modified the wiki and the README.md

Thanks for your feedback!

**Comment by gururajmbhandarkar** [comment]
Works fine now ! Cheers :) 👍
