### ISSUE TITLE
Random order in message.reply

### ISSUE THREAD

**Issue by mycaule** [RecastAI/SDK-NodeJS#27]
Using this function : 

https://github.com/RecastAI/SDK-NodeJS/blob/master/src/apis/resources/message.js#L25

```
const msgs = [
    { type: 'text', content: '1' },
    { type: 'text', content: '2' },
    { type: 'text', content: '3'}
  ];
  message.reply(msgs).then(() => {
    console.log('Done');
  })
  .catch(err => console.error('Error while sending message to channel', err));
```

The order of the messages is not met in the Microsoft Bot Framework channel.

There might be an asynchronism problem with this endpoint : https://api.recast.ai/connect/v1/conversations/:conversation_id/messages

**Comment by mycaule** [comment]
You need to use a queue in the backend side of https://api.recast.ai/
See https://caolan.github.io/async/docs.html#queue

**Comment by dbousque** [comment]
Hi there :) A fix is on it's way, it should be released in the following days. For now you can simply wait a little like so :
```javascript
const msgs = [
  { type: 'text', content: '1' },
  { type: 'text', content: '2' },
  { type: 'text', content: '3'}
];
message.reply([msgs[0]]).then(() => console.log('done'));
setTimeout(() => message.reply([msgs[1]]).then(() => console.log('done')), 1000);
setTimeout(() => message.reply([msgs[2]]).then(() => console.log('done')), 2000);
```
Or wait for the promise to resolve and send the next message after that.

**Comment by mycaule** [comment]
I will wait, thank you for your responsiveness.

**Comment by dbousque** [comment]
The fix should be in production now :)
