### ISSUE TITLE
node_modules error when i published on azure app service

### ISSUE THREAD

**Issue by Reminouche** [RecastAI/SDK-NodeJS#3]
Hi,

I developped a bot with recastAI. On local, everthings work... but when i tried to publish my app on azure app service it fails.

`Application has thrown an uncaught exception and is terminated:
Error: Cannot find module './internal/applyEach'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\recastai\node_modules\form-data\node_modules\async\applyEach.js:7:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)`

**Comment by jhoudan** [comment]
Hi !

Can you describe the flow you're using to deploy your bot ?

**Comment by Reminouche** [comment]
I used the regular deployment of Azure app service. I think it checks if a package.json exists, and launch npm install and npm start.

I will try to find azure documentation about deployment and paste it here.

**Comment by Reminouche** [comment]
This is my package.json :

`{
  "name": "fnac-bot",
  "version": "1.0.0",
  "description": "A starter kit for making a bot connected with microsoft bot connector",
  "main": "src/bot.js",
  "scripts": {
    "start": "node src/bot.js"
  },
  "babel": {
    "presets": [
      "es2015",
      "stage-0"
    ]
  },
  "author": "hcherchi",
  "license": "ISC",
  "dependencies": {
    "@slack/client": "^3.6.0",
    "babel-cli": "^6.11.4",
    "babel-eslint": "^6.1.2",
    "babel-preset-es2015": "^6.13.2",
    "babel-preset-stage-0": "^6.5.0",
    "babel-register": "^6.11.6",
    "lodash.mean": "^4.1.0",
    "lodash.meanby": "^4.10.0",
    "recastai": "^2.2.1"
  },
  "devDependencies": {
    "azure-storage": "^1.3.1",
    "moment": "^2.15.1",
    "quiche": "^0.1.0",
    "request-promise": "^4.1.1"
  },
  "engines":{"node": "6.7.0"}
}
`

**Comment by Reminouche** [comment]
Azure App Service understands package.json and npm-shrinkwrap.json files and can install modules based on entries in these files.

https://azure.microsoft.com/en-us/documentation/articles/nodejs-use-node-modules-azure-apps/

**Comment by jhoudan** [comment]
If you have a npm-shrinkwrap module, can you post it the content here?

Do you still have this issue if you remove the 'engines' fields in your package.json?
