### ISSUE TITLE
build.getConversation error 404 "Resource not found"

### ISSUE THREAD

**Issue by shprman** [RecastAI/SDK-NodeJS#34]
Dear Recast developers,

with pseudo-placeholders "my_name" and "my_bot_name":

`this.build.getConversation('my_name', 'my_bot_name', 2).then(res => {console.log(res)})`

returns

> Error: cannot GET /build/v1/users/my_name/bots/my_bot_name/builders/v1/conversation_states/2

even if I definitely know that the conversation ID exists, because I can successfully call

`sendDialogText(text, callback) {
        this.build.dialog(
            { 'type': 'text', content: text },
            { conversationId: 2 })
            .then(res => {
                callback(JSON.parse(JSON.stringify(res)))                
            })
    }`

Am I doing something wrong?

Thanks for your help,
Simon

**Comment by dbousque** [comment]
Hi @shprman, your code works fine for me, are you sure that your user name and your bot name match your token ?

**Comment by shprman** [comment]
Ok, so I need to use the Developer Token, not the Request Token... :)

**Comment by dbousque** [comment]
Hi @shprman, sorry for the inconvenience, it isn't very clear that the developer token is required :)
