### ISSUE TITLE
Debug Mode Error: Parameter token is missing

### ISSUE THREAD

**Issue by guillempuche** [RecastAI/SDK-NodeJS#35]
I use: 
- Bot Framework
- Recast analyseText()
---------- 
I have a problem with my code only when I **only run all 2 codes on Debug Mode**, but running it without debugging it works. Here there are my codes:

1. **VERSION 1** ->  It **doesn't** work on debug mode!!!
It's individual program = not need more code to work
```
require('dotenv').config();
const recastai = require('recastai').default;
const client = new recastai.request(process.env.RECASTAI_TOKEN, 'ca')

client.analyseText("vull cancelar la operacio")
    .then(function (res) {
        if (res.intent()) {
            console.log('RECAST - Intent: ', res.intent().slug);
            console.log('RECAST - Confidence ' + res.intent().confidence);
        };
    }).catch((err) => console.log(err))
```

2. **VERSION 2** -> It **doesn't** work on debug mode!!!
This version use Bot Framework. This code's an exportable module. The parent module sent the ```session``` object like that: ```<module's_name_imported>.intent(session)```. 

```
/*
    NPL integration with Recast.ai
        https://github.com/RecastAI/SDK-NodeJS/wiki/Analyse-text
*/
require('dotenv').config();
const recastai = require('recastai');
const request = new recastai.request(process.env.RECASTAI_TOKEN, 'ca')

const intent = (session) => {
    if (session.type != "conversationUpdate") {
        request.analyseText(session.text)
            .then(function (res) {
                if (res.intent()) {
                    console.log('RECAST - Intent: ', res.intent().slug);
                    console.log('RECAST - Confidence ' + res.intent().confidence);
                };
            }).catch((err) => console.log(err));
    }
};

module.exports.intent = intent;
```

Here there's the error
> Error: Parameter token is missing

![onpaste 20180314-165320](https://user-images.githubusercontent.com/3519924/37413936-5e21824e-27a8-11e8-9d09-d0afbc9923a5.png)

On Debug Mode for the 2 versions, the client object has ```token = undefined```, but ```language = ca```.

_(Screenshot running version 2)_

![onpaste 20180314-162258](https://user-images.githubusercontent.com/3519924/37413082-81cc5ba8-27a6-11e8-92fa-9a0e64f40188.png)

I think the error has something in common with [Github Recast/SDK-Nodejs](https://github.com/RecastAI/SDK-NodeJS/blob/534d2e404d0530201b510ebc26ad87c58c1596e2/spec/test.js#L82)

What's the problem?

**Comment by dbousque** [comment]
As far as Recast is concerned, the two snippets are exactly equivalent, so the issue is not linked to Recast. What do you mean by "debug mode" ? What do you mean by "it's not working" ? What is the `session` object like ? Does it have a `type` field, and is it's value "conversationUpdate" ?

**Comment by guillempuche** [comment]
How can I set on the environment variables on debug mode? All others .env variables work well.

**Comment by dbousque** [comment]
You should first check that `process.env.RECASTAI_TOKEN` is indeed not defined, you can do that by putting a `console.log(process.env.RECASTAI_TOKEN)` (for example) at the very start of the file.

**Comment by guillempuche** [comment]
Thanks! Do it this I've checked that **all** my environment variables were ``undefined``

I run my code on VSCode IDE. On launch.json file:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "nlp-test",
            "program": "${workspaceFolder}/test/botframework-demo/nlp-test.js",
            "env": {
                "NODE_ENV": "development",
            }
        }
    ]
}
```
... I've added 
```
"env": {
     "NODE_ENV": "development",
}
```

Now it works!!! I read about here [VSCode/issues](https://github.com/Microsoft/vscode/issues/102#issuecomment-242420626)
