### ISSUE TITLE
npm install returns a bunch of module not found errors

### ISSUE THREAD

**Issue by Amit-Kolambikar** [RecastAI/SDK-NodeJS#6]
Running npm install --save recastai results in the following erros :
`
Failed to compile.

Error in ./~/defaultable/t/api.js
Module not found: 'tap' in /home/amit/Projects/Maverick/node_modules/defaultable/t

 @ ./~/defaultable/t/api.js 17:11-25

Error in ./~/defaultable/t/defaults.js
Module not found: 'tap' in /home/amit/Projects/Maverick/node_modules/defaultable/t

 @ ./~/defaultable/t/defaults.js 17:11-25

Error in ./~/defaultable/t/merge.js
Module not found: 'tap' in /home/amit/Projects/Maverick/node_modules/defaultable/t

 @ ./~/defaultable/t/merge.js 17:11-25

Error in ./~/defaultable/t/require.js
Module not found: 'tap' in /home/amit/Projects/Maverick/node_modules/defaultable/t

 @ ./~/defaultable/t/require.js 17:11-25

Error in ./~/native-dns/lib/server.js
Module not found: 'dgram' in /home/amit/Projects/Maverick/node_modules/native-dns/lib

 @ ./~/native-dns/lib/server.js 23:12-28

Error in ./~/native-dns/lib/utils.js
Module not found: 'dgram' in /home/amit/Projects/Maverick/node_modules/native-dns/lib

 @ ./~/native-dns/lib/utils.js 21:12-28

Error in ./~/native-dns-cache/lookup.js
Module not found: 'dgram' in /home/amit/Projects/Maverick/node_modules/native-dns-cache

 @ ./~/native-dns-cache/lookup.js 21:12-28

`

![Image Reference](http://i.imgur.com/CM04hEX.png)

**Comment by jhoudan** [comment]
Your error shows that a package called 'defaultable' is missing.
It's not a package the Recast.AI's SDK have in dependency, do you have any other module installed in your project?
Have you tried to install it?

**Comment by Amit-Kolambikar** [comment]
I went on an unistalling npm packages spree starting from defaultable -> native-dns -> dgram -> socks-proxy-agent -> proxy-agent to this : 

`
Failed to compile.

Error in ./~/recastai/lib/class/client.js
Module not found: 'superagent-proxy' in /home/amit/Projects/Maverick/node_modules/recastai/lib/class

 @ ./~/recastai/lib/class/client.js 33:42-69

Error in ./~/recastai/lib/class/conversation.js
Module not found: 'superagent-proxy' in /home/amit/Projects/Maverick/node_modules/recastai/lib/class

 @ ./~/recastai/lib/class/conversation.js 27:42-69



`
